name: 'Close stale issues and PRs'
on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 1 */2 *' #run every 2 months at Midnight first day of the month (https://crontab.guru/#0_0_1_*/2_*)
  
######################################
#    Set Permissions for the token   #
######################################
#More information found here: --> https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
permissions:
  contents: read
  #deployments: read
  #id-token: read
  issues: read
  #metadata: read set to read by default
  #packages: read
  #pages: read
  #pull-requests: read
  #repository-projects: read
  #security-events: read
  statuses: write
     
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          stale-issue-message: 'Your issue is over 60 days old. Closing issue.'
          stale-pr-message: 'Please comment on this PR, it is over 60 days old. This will close if no comment is submitted.'
