#################################################################################################
# Beginning of the YML file                                                                     #
# documentation can be found here: https://yaml.org/spec/1.2.2/#chapter-1-introduction-to-yaml) #
#################################################################################################
name: VitoCI   #name of workflow as it will appear in Actions
on:
  workflow_dispatch: #allows you use run the workflow manually in github actions
  #push:
  #  branches: [CICD-TEST]
  #pull_request:
  #  branches: [CICD-TEST]
######################################
#    Set Permissions for the token   #   
######################################
#More information found here: --> https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
permissions:
  contents: read
  #deployments: read
  #id-token: read
  issues: read
  #metadata: read set to read by default
  #packages: read
  #pages: read
  #pull-requests: read
  #repository-projects: read
  #security-events: read
  statuses: write

    


jobs:
  Linting: #name this whatever you want the job id to be called
    name: Job-1  #this is what will appear as the job name in Actions
    runs-on: ubuntu-latest

    steps:
      #################################################
      # Checkout code for the VM checking your repo   #
      #################################################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      ######################################
      # Run Super-Linter against code base #
      ######################################
      - name: Super-Linter Slimv4
      #calling the Super-Linter slimv4 to exclude rust,dotenv,armttk,pwsh,and c# linters
        uses: github/super-linter/slim@v4
        env:
          LINTER_RULES_PATH: /RULES
          VALIDATE_ALL_CODEBASE: true ####set this to true if you want to test your entire code base even if there are not changes, or false if not
          DEFAULT_BRANCH: CICD-TEST
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #ACTIONS_RUNNER_DEBUG: true   #in case of needing to debug issues with runner
      #################################################
      # Remove linters where languages are not in use #
      #################################################
          #VALIDATE_ANSIBLE: false
          #VALIDATE_ARM: false
          #VALIDATE_BASH: false
          #VALIDATE_CLANG_FORMAT: false
          #VALIDATE_CLOJURE: false
          #VALIDATE_CLOUDFORMATION: false
          #VALIDATE_DART: false
          #VALIDATE_GO: false
          #VALIDATE_GOOGLE_JAVA_FORMAT: false
          #VALIDATE_GROOVY: false
          #VALIDATE_KUBERNETES_KUBEVAL: false
          #VALIDATE_PERL: false
          #VALIDATE_POWERSHELL: false
          #VALIDATE_PROTOBUF: false
          #################################################
          CSS_FILE_NAME: .stylelintrc.json #use our rules for linting scss
          

        
